export const AGREGAR_TITULAR = 'AGREGAR_TITULAR';
export const AGREGAR_SUPLENTE = 'AGREGAR_SUPLENTE';
export const QUITAR_TITULAR = 'QUITAR_TITULAR';
export const QUITAR_SUPLENTE = 'QUITAR_SUPLENTE';
